name: Pre-merge checks

on:
  pull_request:
    branches:
      - main
      - "releases/**"

permissions: {}

jobs:
  zizmor-scan-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Run Zizmor scan
        uses: open-edge-platform/anomalib/.github/actions/security/zizmor@4733f2f43fe6477952936d0ce114c4ea513e0f79
        with:
          scan-scope: "changed"
          severity-level: "MEDIUM"
          confidence-level: "HIGH"
          fail-on-findings: true
  bandit-scan-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Run Bandit scan
        uses: open-edge-platform/anomalib/.github/actions/security/bandit@4733f2f43fe6477952936d0ce114c4ea513e0f79
        with:
          scan-scope: "changed"
          severity-level: "MEDIUM"
          confidence-level: "HIGH"
          config_file: ".github/bandit_config.yml"
          fail-on-findings: true
